---
# -------- GENERAL -------- #
- include: variables.yml
  tags: "always"

- include: swap.yml
  tags: "swap"

- include: config.yml
  tags: "config"

- include: upgrade.yml
  tags: "upgrade"

- include: install.yml
  tags: "install"

- include: root.yml
  tags: "root"

- include: admin.yml
  tags: "admin"

- include: sshd.yml
  tags: "sshd"

- include: firewall.yml
  tags: "firewall"

- include: restic.yml
  tags: "restic"

- include: node-exporter.yml
  tags: "node-exporter"

# -------- WEBSERVER -------- #
- name: "include webserver tasks"
  include_tasks: main-webserver.yml
  when:
    - server_type == 'webserver'

# -------- LOADBALANCER -------- #
- name: "include loadbalancer tasks"
  include_tasks: main-loadbalancer.yml
  when:
    - server_type == 'loadbalancer'

# -------- CLEANUP -------- #
- include: cleanup.yml
  tags: "cleanup"
