version: "3.3"

services:
  autopilot:
    image: sitepilot/autopilot-base:${APP_DOCKER_TAG:-latest}
    container_name: autopilot
    depends_on:
      - mysql
      - redis
    ports:
      - "${APP_HTTP_PORT:-8080}:80"
      - "${APP_HTTPS_PORT:-8443}:443"
    restart: always
    environment:
      AUTOPILOT_URL: ${APP_URL}
      AUTOPILOT_USER_ID: ${APP_USER_ID:-1000}
      AUTOPILOT_USER_GID: ${APP_USER_GID:-1000}
      AUTOPILOT_CERT_EMAIL: ${APP_CERT_EMAIL:-internal}
      AUTOPILOT_MONITOR_PASSWORD: ${APP_MONITOR_PASSWORD:-supersecret}
      AUTOPILOT_MONITOR_SLACK_WEBHOOK: ${APP_MONITOR_SLACK_WEBHOOK:-https://hooks.slack.com/services/xxxx/xxxx/xxxx}
      AUTOPILOT_MONITOR_SLACK_CHANNEL: ${APP_MONITOR_SLACK_CHANNEL:-monitoring}
    volumes:
      - "./:/var/www/html"
      - "./data/prometheus:/etc/prometheus/data"
      - "./data/alertmanager:/etc/alertmanager/data"

  mysql:
    image: mariadb:10.4-bionic
    container_name: autopilot-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "mysql_data:/var/lib/mysql"

  redis:
    image: "redis:alpine"
    container_name: autopilot-redis
    restart: always
    volumes:
      - redis_data:/var/lib/redis

  grafana:
    image: sitepilot/autopilot-grafana:${APP_GRAFANA_TAG:-latest}
    container_name: autopilot-grafana
    depends_on:
      - autopilot
    restart: always
    volumes:
      - "grafana_data:/var/lib/grafana"
 
  test:
    build: ./docker/test
    container_name: autopilot-test
    restart: always
    privileged: true
    ports:
      - "${APP_TEST_HTTP_PORT:-20080}:80"
      - "${APP_TEST_HTTPS_PORT:-20443}:443"
      - "${APP_TEST_LITESPEED_PORT:-22083}:2083"
      - "${APP_TEST_SSH_PORT:-20022}:22"
      - "${APP_TEST_NODE_EXPORTER_PORT:-29100}:9100"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"

  test-lb:
    build: ./docker/test
    container_name: autopilot-test-lb
    restart: always
    privileged: true
    ports:
      - "${APP_TEST_LB_HTTP_PORT:-30080}:80"
      - "${APP_TEST_LB_HTTPS_PORT:-30443}:443"
      - "${APP_TEST_LB_NODE_EXPORTER_PORT:-39100}:9100"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"

volumes:
  mysql_data:
  redis_data:
  grafana_data:
