version: "3.3"

services:
  mysql:
    image: mariadb:10.4-bionic
    container_name: autopilot-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./data/mysql:/var/lib/mysql"

  redis:
    image: "redis:alpine"
    container_name: autopilot-redis
    restart: always
    volumes:
      - ./data/redis:/var/lib/redis

  autopilot:
    image: sitepilot/autopilot:${APP_DOCKER_TAG:-latest}
    container_name: autopilot
    depends_on:
      - mysql
    ports:
      - "${APP_HTTP_PORT:-8080}:80"
      - "${APP_HTTPS_PORT:-8443}:443"
    restart: always
    environment:
      WEBSERVER_USER_ID: ${APP_USER_ID:-1000}
      WEBSERVER_USER_GID: ${APP_USER_GID:-1000}
    volumes:
      - "./.env:/var/www/html/.env"
      - "./data/app:/var/www/html/storage/app"
      - "./data/vendor:/var/www/html/vendor"

  prometheus:
    image: sitepilot/autopilot-prometheus:${APP_PROMETHEUS_TAG:-latest}
    container_name: autopilot-prometheus
    depends_on:
      - autopilot
    restart: always
    volumes:
      - "./data/app/monitor/servers.json:/etc/prometheus/autopilot-servers.json"
      - "./data/app/monitor/domains.json:/etc/prometheus/autopilot-domains.json"
      - "prometheus_data:/prometheus"
    ports:
      - "${APP_PROMETHEUS_PORT:-127.0.0.1:9090}:9090"

  alertmanager:
    image: sitepilot/autopilot-alertmanager:${APP_ALERTMANAGER_TAG:-latest}
    container_name: autopilot-alertmanager
    depends_on:
      - prometheus
    restart: always
    volumes:
      - "alertmanager_data:/alertmanager"
    ports:
      - "${APP_ALERTMANAGER_PORT:-127.0.0.1:9093}:9093"
    environment:
      ALERTMANAGER_SLACK_WEBHOOK: "${APP_MONITOR_SLACK_WEBHOOK:-https://hooks.slack.com/services/xxxx/xxxx/xxxx}"

  blackbox:
    image: sitepilot/autopilot-blackbox:${APP_BLACKBOX_TAG:-latest}
    container_name: autopilot-blackbox
    depends_on:
      - prometheus
    restart: always
    ports:
      - "${APP_BLACKBOX_PORT:-127.0.0.1:9115}:9115"

  grafana:
    image: sitepilot/autopilot-grafana:${APP_GRAFANA_TAG:-latest}
    container_name: autopilot-grafana
    depends_on:
      - prometheus
    restart: always
    ports:
      - "${APP_GRAFANA_PORT:-2096}:3000"
    volumes:
      - "grafana_data:/var/lib/grafana"

volumes:
  grafana_data:
  prometheus_data:
  alertmanager_data:
