version: "3.3"

services:
  test:
    build: ./docker
    container_name: autopilot-test
    restart: always
    privileged: true
    ports:
      - "${APP_TEST_HTTP_PORT:-20080}:80"
      - "${APP_TEST_HTTPS_PORT:-20443}:443"
      - "${APP_TEST_LITESPEED_PORT:-22083}:2083"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"

  test-lb:
    build: ./docker
    container_name: autopilot-test-lb
    restart: always
    privileged: true
    ports:
      - "${APP_TEST_LB_HTTP_PORT:-30080}:80"
      - "${APP_TEST_LB_HTTPS_PORT:-30443}:443"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
