version: "3.3"

services:
  test-web:
    image: sitepilot/autopilot-test:20.04
    container_name: autopilot-test
    restart: always
    privileged: true
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    networks:
      testing_net:
        ipv4_address: ${TEST_WEB_IP:-172.25.1.1}

  test-lb:
    image: sitepilot/autopilot-test:20.04
    container_name: autopilot-test-lb
    restart: always
    privileged: true
    cap_add:
      - NET_ADMIN
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    networks:
      testing_net:
        ipv4_address: ${TEST_LB_IP:-172.25.1.2}

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
