version: "3.3"

services:
  test:
    build: ./docker
    container_name: autopilot-test
    restart: always
    privileged: true
    ports:
      - "${APP_TEST_HTTP_PORT}:80"
      - "${APP_TEST_HTTPS_PORT}:443"
      - "${APP_TEST_LITESPEED_PORT}:2083"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
