---
- hosts: "all"
  vars:
    user: ""
    key: ""
    comment: ""
  tasks:
    - name: "key/provision : {{ user }} : add key to authorized keys"
      authorized_key:
        user: "{{ user }}"
        state: "present"
        key: "{{ key }}"
        comment: "{{ comment }}"
