---
- hosts: "all"
  vars:
    #user: ""
    #full_name: ""
    #email: ""
    #password: ""
    #mysql_password: ""
    #isolated: true
    #private_key: ""
    #public_key: ""
    path: "/opt/sitepilot/users/{{ user }}"
  tasks:
    - name: "user/provision : {{ user }} : ensure 'isolated' group exists"
      group:
        name: "isolated"
        state: present

    - name: "user/provision : {{ user }} : install required pip packages"
      pip:
        name: "{{ item }}"
        state: present
      loop:
        - PyMySQL

    - name: "user/provision : {{ user }} : ensure user group '{{ user }}' exists"
      group:
        name: "{{ user }}"
        state: present

    - name: "user/provision : {{ user }} : ensure user exists"
      user:
        name: "{{ user }}"
        group: "{{ user }}"
        groups: "isolated"
        shell: "/bin/bash"
        password: "{{ password | password_hash('sha512') }}"
        comment: "{{ full_name if (full_name is defined) and (full_name|length > 0) else user }}"

    - name: "user/provision : {{ user }} : create folders"
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.owner }}"
        mode: "{{ item.mode }}"
      loop:
        - path: "{{ path }}"
          owner: "root"
          mode: "0750"
        - path: "{{ path }}/sites"
          owner: "{{ user }}"
          mode: "0750"
        - path: "/home/{{ user }}/.ssh/"
          owner: "{{ user }}"
          mode: "0700"

    - name: "user : {{ user }} : setup ACL"
      acl:
        path: "{{ path }}"
        entity: "{{ item.entity }}"
        etype: "{{ item.etype }}"
        permissions: "{{ item.permissions }}"
        default: "{{ item.default }}"
        recursive: "{{ item.recursive }}"
        state: present
      loop:
        - entity: "{{ user }}" # allow user to read files
          etype: group
          permissions: rx
          default: no
          recursive: no
        - entity: sitepilot # allow sitepilot group to read files
          etype: group
          permissions: rx
          default: no
          recursive: yes
        - entity: sitepilot
          etype: group
          permissions: rx
          default: yes
          recursive: yes

    - name: "user/provision : {{ user }} : create symlink to sites folder"
      file:
        src: "{{ path }}/sites"
        dest: "/home/{{ user }}/sites"
        state: link

    - name: "user/provision : {{ user }} : set home dir permission"
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0700"
      loop:
        - "/home/{{ user }}"

    - name: "user : {{ user }} : remove isolated group"
      user:
        name: "{{ user }}"
        groups: ""
      when:
        - isolated is defined
        - not isolated

    - name: "user : {{ user }} : create database user"
      mysql_user:
        name: "{{ user }}"
        password: "{{ mysql_password }}"
        priv: "{{ user }}_%.*:SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE TEMPORARY TABLES,EXECUTE,CREATE VIEW,SHOW VIEW,CREATE ROUTINE,ALTER ROUTINE,EVENT,TRIGGER,DROP"
        state: present
        host: "%"
        config_file: "/root/.my.cnf"
      when:
        - mysql_password is defined
        - mysql_password | length > 0
      no_log: true

    - name: "user : {{ user }} : save private key"
      copy:
        content: "{{ private_key }}"
        dest: "/home/{{ user }}/.ssh/id_rsa"
        force: yes
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0600"
      when:
        - private_key is defined
        - private_key | length > 0

    - name: "user : {{ user }} : save public key"
      copy:
        content: "{{ public_key }}"
        dest: "/home/{{ user }}/.ssh/id_rsa.pub"
        force: yes
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0600"
      when:
        - public_key is defined
        - public_key | length > 0
