---
- name: "redis : create service folders"
  file:
    path: "{{ item }}"
    owner: "1001"
    group: "1001"
    state: directory
    mode: "0700"
  loop:
    - /opt/sitepilot/services/redis/
    - /opt/sitepilot/services/redis/data/

- name: "redis : generate Docker Compose configuration"
  template:
    src: redis_docker_compose.j2
    dest: /opt/sitepilot/services/redis/docker-compose.yml

- name: "redis : start containers"
  docker_compose:
    project_src: /opt/sitepilot/services/redis
