---
- name: "phpmyadmin : create service folders"
  file:
    path: "{{ item }}"
    owner: "1001"
    group: "1001"
    state: directory
    mode: "0700"
  loop:
    - /opt/sitepilot/services/phpmyadmin/conf/

- name: "phpmyadmin : generate configuration"
  template:
    src: pma_config.inc.php.j2
    dest: /opt/sitepilot/services/phpmyadmin/conf/config.inc.php
    owner: "1001"
    group: "1001"

- name: "phpmyadmin : generate Docker Compose configuration"
  template:
    src: pma_docker_compose.j2
    dest: /opt/sitepilot/services/phpmyadmin/docker-compose.yml

- name: "phpmyadmin : start containers"
  docker_compose:
    project_src: /opt/sitepilot/services/phpmyadmin
