---
- name: "fail2ban : install required packages"
  apt:
    name: "fail2ban"
    state: present

- name: "fail2ban : generate filter configuration"
  template:
    src: fail2ban_filter.j2
    dest: /etc/fail2ban/filter.d/sitepilot.conf
  notify: restart fail2ban
