global:
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/alerts/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - autopilot-alertmanager:9093

scrape_configs:
  - job_name: "servers"
    file_sd_configs:
      - files:
          - "/etc/prometheus/autopilot-servers.json"

  - job_name: "domains"
    metrics_path: /probe
    scrape_interval: 5m
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
          - "/etc/prometheus/autopilot-domains.json"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: autopilot-blackbox:9115
