---
- name: "firewall : install required packages"
  apt:
    name: "ufw"
    state: present

- name: "firewall : allow default services"
  ufw:
    port: "{{ item.port }}"
    comment: "{{ item.comment }}"
    rule: allow
  loop:
    - port: 80
      comment: "proxy http"
    - port: 443
      comment: "proxy https"
    - port: 7082
      comment: "web https"
    - port: 22
      comment: "ssh"
    - port: 3306
      comment: "mysql"
