---
- name: "firewall : install required packages"
  apt:
    name: "ufw"
    state: present

- name: "firewall : allow default services"
  ufw:
    port: "{{ item.port }}"
    comment: "{{ item.comment }}"
    rule: allow
  loop:
    - port: 80
      comment: "http"
    - port: 443
      comment: "https"
    - port: 22
      comment: "ssh"
    - port: 3306
      comment: "mysql"
    - port: 2083
      comment: "openlitespeed"
