---
- include: swap.yml
  tags: "swap"

- include: config.yml
  tags: "config"

- include: upgrade.yml
  tags: "upgrade"

- include: install.yml
  tags: "install"

- include: pip.yml
  tags: "pip"

- include: filesystem.yml
  tags: "filesystem"

- include: admin.yml
  tags: "admin"

- include: sshd.yml
  tags: "sshd"

- include: restic.yml
  tags: "restic"

- include: ssmtp.yml
  tags: "ssmtp"

- include: docker.yml
  tags: "docker"

- include: "docker-node-exporter.yml"
  tags: "node-exporter"

- include: firewall.yml
  tags: "firewall"
