---
hostname: undefined
hostname_update: false
timezone: Europe/Amsterdam
timezone_update: true
autopilot_host: false

admin: sitepilot
admin_pass: "supersecret"
admin_email: support@sitepilot.io
health_email: health@sitepilot.io

mysql_root_pass: "supersecret"

php_post_max_size: "64"
php_upload_max_filesize: "32"
php_memory_limit: "512"

smtp_relay_host: "smtp.eu.mailgun.org"
smtp_relay_domain: "mg.example.com"
smtp_relay_user: "postmaster@mg.example.com"
smtp_relay_password: "supersecret"

swap_path: "/swapfile"
swap_size: "1024"
swap_swappiness: "60"

pma_version: "5.0.1"
pma_update_version: false
pma_blowfish_secret: "9B3U6iQKBeaoki8n07HZckWxBKCrxlok"
