groups:
  - name: Blackbox
    rules:
      - alert: BlackboxProbeFailed
        expr: probe_success == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.instance }}: probe failed"
          description: "Blackbox probe failed. Value: {{ $value }}"

      - alert: BlackboxSlowProbe
        expr: avg_over_time(probe_duration_seconds[1m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "{{ $labels.instance }}: slow probe"
          description: "Blackbox probe took more than 1s to complete. Value: {{ $value }}"

      - alert: BlackboxProbeHttpFailure
        expr: probe_http_status_code <= 199 OR probe_http_status_code >= 400
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.instance }}: HTTP failure"
          description: "HTTP status code is not 200-399. Value: {{ $value }}"

      - alert: BlackboxSslCertificateWillExpireSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "{{ $labels.instance }}: SSL certificate will expire soon"
          description: "SSL certificate expires in 30 days. Value: {{ $value }}"

      - alert: BlackboxSslCertificateWillExpireSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 3
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.instance }}: SSL certificate will expire soon"
          description: "SSL certificate expires in 3 days. Value: {{ $value }}"

      - alert: BlackboxSslCertificateExpired
        expr: probe_ssl_earliest_cert_expiry - time() <= 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.instance }}: SSL certificate expired"
          description: "SSL certificate has expired already. Value: {{ $value }}"

      - alert: BlackboxProbeSlowHttp
        expr: avg_over_time(probe_http_duration_seconds[1m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "{{ $labels.instance }}: slow HTTP"
          description: "HTTP request took more than 1s. Value: {{ $value }}"

      - alert: BlackboxProbeSlowPing
        expr: avg_over_time(probe_icmp_duration_seconds[1m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "{{ $labels.instance }}: slow ping"
          description: "Blackbox ping took more than 1s. Value: {{ $value }}"
