global:
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/alerts/*.yml"

alerting:
  alertmanagers:
    - path_prefix: "monitor/alertmanager/"
      static_configs:
        - targets:
            - 127.0.0.1:9093

scrape_configs:
  - job_name: "servers"
    file_sd_configs:
      - files:
          - "/var/www/html/storage/app/monitor/servers.json"

  - job_name: "domains"
    metrics_path: /probe
    scrape_interval: 5m
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
          - "/var/www/html/storage/app/monitor/domains.json"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
