---
- hosts: "all"
  vars:
    # source_site: ""
    # source_user: ""
    # mount_site: ""
    # mount_user: ""
    # ssh_host: ""
    sshfs_path: "/sites/{{ source_site }}"
    mount_path: "/opt/sitepilot/users/{{ mount_user }}/sites/{{ mount_site }}"
    source_path: "/opt/sitepilot/users/{{ source_user }}/sites/{{ source_site }}"
  tasks:
    - name: "site/mount/provision  : create local mount for site '{{ source_site }}' to user '{{ mount_user }}'"
      mount:
        path: "{{ mount_path }}"
        src: "{{ source_path }}"
        fstype: fuse.bindfs
        opts: "create-for-user={{ source_user }},create-for-group={{ source_user }},mirror-only={{ mount_user }}"
        state: mounted
      when:
        - ssh_host | length == 0

    - name: "site/mount/provision : create remote mount for site '{{ source_site }}' to user '{{ mount_user }}'"
      mount:
        path: "{{ mount_path }}"
        src: "{{ source_user }}@{{ ssh_host }}:{{ sshfs_path }}"
        fstype: fuse.sshfs
        opts: "identityfile=/home/{{ mount_user }}/.ssh/id_rsa,allow_other,defaults,_netdev,follow_symlinks"
        state: mounted
      when:
        - ssh_host | length > 0
