---
- hosts: "all"
  vars:
    # Required parameters, commented so Ansible fails when a parameter isn't present.
    # user: ""
    # site: ""
    # domains: []
    # email: ""
    # ssl: true
    path: "/opt/sitepilot/users/{{ user }}/{{ site }}"
    path_vhost: "/usr/local/lsws/conf/vhosts/{{ site }}.conf"
  tasks:
    - name: "site/cert : {{ user }} : {{ site }} : request ssl certificate"
      command: "certbot certonly --noninteractive --agree-tos --email {{ email }} --cert-name {{ site }} --webroot -w {{ path }}/public {{ '-d ' + domains|join(' -d ') if domains is defined and domains|length>0 else '' }}"

    - name: "site/cert : {{ user }} : {{ site }} : regenerate vhost configuration"
      template:
        src: ./templates/olsws_site_vhost.j2
        dest: "{{ path_vhost }}"

    - name: "site/cert : {{ user }} : {{ site }} : reload web server"
      service:
        name: lsws
        state: reloaded
