---
- hosts: "all"
  vars:
    # user: ""
    # site: ""
    # domain: ""
    # domains: []
    # php_version: "74"
    # email: ""
    # backends: []
    path: "/opt/sitepilot/users/{{ user }}/sites/{{ site }}"
    path_vhost: "/usr/local/lsws/conf/vhosts/{{ site }}.conf"
    path_proxy: "/etc/caddy/vhosts/{{ site }}.conf"
    path_fail2ban: "/etc/fail2ban/jail.d/{{ site }}.conf"
  tasks:
    - name: "site/provision : {{ user }} : {{ site }} : create folders"
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0755"
      loop:
        - "{{ path }}"
        - "{{ path }}/public"
        - "{{ path }}/logs"

    - name: "site/provision : {{ user }} : {{ site }} : set folder / file permissions"
      command: "{{ item }}"
      loop:
        - "find {{ path }} -type f -exec chmod 644 {} +"
        - "find {{ path }} -type d -exec chmod 755 {} +"

    - name: "site/provision : {{ user }} : {{ site }} : generate vhost configuration"
      template:
        src: ./templates/lshttpd_vhost.j2
        dest: "{{ path_vhost }}"
        owner: "lsadm"
        group: "nogroup"
        mode: "0644"

    - name: "site/provision : {{ user }} : {{ site }} : generate proxy vhost"
      template:
        src: ./templates/caddy_proxy_vhost.j2
        dest: "{{ path_proxy }}"
        owner: "caddy"
        group: "caddy"
        mode: "0644"

    - name: "site/provision : {{ user }} : {{ site }} : generate fail2ban jail"
      template:
        src: ./templates/fail2ban_jail.j2
        dest: "{{ path_fail2ban }}"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: "site/provision : {{ user }} : {{ site }} : reload web server"
      service:
        name: lshttpd
        state: restarted

    - name: "site/provision : {{ user }} : {{ site }} : reload proxy server"
      service:
        name: caddy
        state: reloaded

    - name: "site/provision : {{ user }} : {{ site }} : reload fail2ban"
      service:
        name: fail2ban
        state: reloaded
